"use client";
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {apiFetch} from '../../../../lib/auth';
import {Card} from '../../../../components/ui/Card';
import {Button} from '../../../../components/ui/Button';
import {Input,Select,Textarea} from '../../../../components/ui/Field';

export interface Warehouse {id:string;name:string;isActive:boolean}
interface Product {id:string;name:string;imageUrl:string;unit:string;lowStockThreshold:number}
interface Balance {productId:string;warehouseId:string;available:number;reserved:number;version:number}
interface LocationData {warehouses:Warehouse[];balances:Balance[];unassigned:{productId:string;available:number;reserved:number}[];legacyOrders:{id:string;pickupCenterId:string|null;pickupCenterName:string|null;status:string}[]}
interface Entry {id:string;productName:string;unit:string;warehouseName:string;kind:string;availableBefore:number;availableAfter:number;reservedBefore:number;reservedAfter:number;reason:string;reference:string|null;actorName:string|null;operationId:string|null;orderId:string|null;createdAt:string}
type Action='allocation'|'transfer'|'count';
interface Form {kind:Action;productId:string;warehouseId:string;destinationId:string;quantity:string;reason:string;reference:string;operationId:string;expectedVersion:number}
async function request<T>(path:string,options?:RequestInit):Promise<T>{const r=await apiFetch(`/v1/admin/inventory${path}`,options);const b=await r.json();if(!r.ok)throw new Error(typeof b.message==='string'?b.message:'Check the fields and try again.');return b;}

export default function WarehousePanel({products,revision,onChanged,onLocations}:{products:Product[];revision:number;onChanged:()=>void;onLocations:(rows:Warehouse[])=>void}){
 const [data,setData]=useState<LocationData|null>(null);const [location,setLocation]=useState('unassigned');
 const [form,setForm]=useState<Form|null>(null);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
 const [search,setSearch]=useState('');const [page,setPage]=useState(1);const [historyPage,setHistoryPage]=useState(1);
 const [history,setHistory]=useState<{items:Entry[];total:number;pageSize:number}|null>(null);const [historyError,setHistoryError]=useState('');
 const [legacyId,setLegacyId]=useState('');const [legacyWarehouse,setLegacyWarehouse]=useState('');
 useEffect(()=>{let active=true;request<LocationData>('/warehouses').then(d=>{if(active){setData(d);onLocations(d.warehouses);setError('');}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[revision,onLocations]);
 useEffect(()=>{let active=true;setHistory(null);setHistoryError('');request<{items:Entry[];total:number;pageSize:number}>(`/warehouse-movements?page=${historyPage}${location!=='unassigned'?`&warehouseId=${location}`:''}`).then(h=>{if(active)setHistory(h);}).catch(e=>{if(active)setHistoryError(e.message);});return()=>{active=false;};},[revision,location,historyPage]);
 function balance(productId:string){return location==='unassigned'?{...(data?.unassigned.find(b=>b.productId===productId)??{available:0,reserved:0}),version:1}:data?.balances.find(b=>b.warehouseId===location&&b.productId===productId)??{available:0,reserved:0,version:1};}
 function start(p:Product,kind:Action){const b=balance(p.id);setForm({kind,productId:p.id,warehouseId:kind==='allocation'?'':location,destinationId:'',quantity:kind==='count'?String(b.available+b.reserved):'',reason:'',reference:'',operationId:crypto.randomUUID(),expectedVersion:b.version});setError('');setNotice('');}
 function change(update:Partial<Form>){setForm(f=>f?{...f,...update,operationId:crypto.randomUUID()}:null);}
 async function save(e:React.FormEvent){e.preventDefault();if(!form||busy)return;setBusy(true);setError('');try{
  const body={productId:form.productId,warehouseId:form.warehouseId,operationId:form.operationId,reason:form.reason.trim(),reference:form.reference.trim(),...(form.kind==='count'?{onHand:Number(form.quantity),expectedVersion:form.expectedVersion}:{quantity:Number(form.quantity)}),...(form.kind==='transfer'?{destinationId:form.destinationId}:{})};
  await request(`/${form.kind==='allocation'?'allocations':form.kind==='transfer'?'transfers':'counts'}`,{method:'POST',body:JSON.stringify(body)});
  setNotice(form.kind==='allocation'?'Existing stock assigned. The total has not changed.':form.kind==='transfer'?'Transfer posted. Stock totals are unchanged.':'Physical count posted with its adjustment.');setForm(null);onChanged();
 }catch(e){setError(e instanceof Error?e.message:'Unable to post warehouse action');}finally{setBusy(false);}}
 async function assignLegacy(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{await request(`/legacy-orders/${legacyId}/warehouse`,{method:'POST',body:JSON.stringify({warehouseId:legacyWarehouse})});setNotice('Existing order reservation assigned without deducting stock again.');setLegacyId('');setLegacyWarehouse('');onChanged();}catch(e){setError(e instanceof Error?e.message:'Unable to assign order');}finally{setBusy(false);}}
 const filtered=products.filter(p=>p.name.toLowerCase().includes(search.toLowerCase()));const pages=Math.max(1,Math.ceil(filtered.length/10));const currentPage=Math.min(page,pages);
 const selected=products.find(p=>p.id===form?.productId);const activeLocations=data?.warehouses.filter(w=>w.isActive)??[];
 return <section className="space-y-4"><div><h2 className="text-xl font-semibold">Stock by pickup warehouse</h2><p className="mt-1 text-sm text-text-muted">Assign opening stock, move goods between locations and record physical counts.</p></div>
 {error&&<p role="alert" className="rounded-lg bg-error/10 p-3 text-sm text-error">{error}</p>}{notice&&<p role="status" className="rounded-lg bg-primary/10 p-3 text-sm text-primary">{notice}</p>}
 {!data?<p>Loading warehouse balances…</p>:<>
 <div className="grid gap-4 sm:grid-cols-2"><Select label="Warehouse" value={location} disabled={busy} onChange={e=>{setLocation(e.target.value);setPage(1);setHistoryPage(1);setForm(null);}}><option value="unassigned">Unassigned stock</option>{data.warehouses.map(w=><option key={w.id} value={w.id}>{w.name}{w.isActive?'':' (inactive)'}</option>)}</Select><Input label="Find product" type="search" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Search products…" /></div>
 {location!=='unassigned'&&data.unassigned.some(s=>s.available>0)&&<p className="inventory-explainer rounded-xl p-4 text-sm text-emerald-800">Opening stock remains unassigned. Select Unassigned stock and allocate it before recording your first physical count.</p>}
 {data.warehouses.length===1&&<p className="text-xs text-text-muted">To transfer stock between warehouses, <Link className="text-primary underline" href="/dashboard/pickup-centers">add another pickup centre</Link>.</p>}
 {location==='unassigned'&&<p className="inventory-explainer rounded-xl p-4 text-sm text-emerald-800">Unassigned stock is included in the overall total. Allocate it to the location where it is held before accepting new pickup orders. Allocation does not receive new stock.</p>}
 {form&&<Card className="p-5"><form onSubmit={save} className="space-y-4"><h3 className="font-semibold">{form.kind==='allocation'?'Assign existing stock':form.kind==='transfer'?'Transfer stock':'Physical stock count'} — {selected?.name}</h3>
 {form.kind==='allocation'?<Select label="Destination pickup warehouse" required value={form.warehouseId} disabled={busy} onChange={e=>change({warehouseId:e.target.value})}><option value="">Choose warehouse</option>{activeLocations.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</Select>:<p className="text-sm">Warehouse: {data.warehouses.find(w=>w.id===form.warehouseId)?.name}</p>}
 {form.kind==='transfer'&&<Select label="Transfer to" required disabled={busy} value={form.destinationId} onChange={e=>change({destinationId:e.target.value})}><option value="">Choose destination</option>{activeLocations.filter(w=>w.id!==form.warehouseId).map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</Select>}
 <div className="grid gap-4 sm:grid-cols-2"><Input label={form.kind==='count'?`Counted on hand (${selected?.unit})`:`Quantity (${selected?.unit})`} required disabled={busy} type="number" min={form.kind==='count'?balance(form.productId).reserved:1} max="1000000" step="1" value={form.quantity} onChange={e=>change({quantity:e.target.value})}/><Input label="Reference (optional)" disabled={busy} maxLength={160} value={form.reference} onChange={e=>change({reference:e.target.value})}/></div>
 {form.kind==='count'&&<p className="text-sm text-text-muted">Include reserved goods in the physical count. Reserved: {balance(form.productId).reserved}. Stock changes after you open this form will require a fresh count.</p>}
 <Textarea label="Reason" required disabled={busy} minLength={3} maxLength={500} value={form.reason} onChange={e=>change({reason:e.target.value})}/><div className="flex gap-3"><Button type="submit" disabled={busy}>{busy?'Posting…':form.kind==='allocation'?'Allocate stock':form.kind==='transfer'?'Post transfer':'Record count'}</Button><Button type="button" variant="ghost" disabled={busy} onClick={()=>setForm(null)}>Cancel</Button></div></form></Card>}
 <Card className="inventory-table warehouse-table overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead><tr>{['Product','Available','Reserved','On hand','Status','Actions'].map(t=><th className="p-3" key={t}>{t}</th>)}</tr></thead><tbody>{filtered.slice((currentPage-1)*10,currentPage*10).map(p=>{const b=balance(p.id);return <tr key={p.id} className="border-t border-slate-100"><td className="p-3"><div className="flex items-center gap-3"><img src={p.imageUrl} alt="" className="h-14 w-14 rounded-lg object-contain"/><div><p className="font-semibold">{p.name}</p><p className="text-xs text-text-muted">{p.unit}</p></div></div></td><td className="p-3 font-semibold text-primary">{b.available}</td><td className="p-3">{b.reserved}</td><td className="p-3">{b.available+b.reserved}</td><td className="p-3"><span className={`rounded-full px-2 py-1 text-xs ${b.available===0?"bg-error/10 text-error":b.available<=p.lowStockThreshold?"bg-gold/10 text-gold-dark":"bg-primary/10 text-primary"}`}>{b.available===0?"Out of stock":b.available<=p.lowStockThreshold?"Low stock":"In stock"}</span></td><td className="p-3">{location==='unassigned'?<Button disabled={busy||b.available<=0||!activeLocations.length} onClick={()=>start(p,'allocation')}>Allocate</Button>:<div className="flex gap-2"><Button disabled={busy||b.available<=0||!activeLocations.some(w=>w.id!==location)} onClick={()=>start(p,'transfer')}>Transfer</Button><Button variant="ghost" disabled={busy} onClick={()=>start(p,'count')}>Count</Button></div>}</td></tr>;})}</tbody></table><div className="flex items-center justify-between p-3 text-xs"><Button variant="ghost" disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}>Previous</Button><p>Page {currentPage} of {pages} · {filtered.length} products</p><Button variant="ghost" disabled={currentPage===pages} onClick={()=>setPage(currentPage+1)}>Next</Button></div></Card>
 {!!data.legacyOrders.length&&<Card className="p-5"><form onSubmit={assignLegacy} className="space-y-3"><h3 className="font-semibold">Existing order reservations awaiting a warehouse</h3><p className="text-sm text-text-muted">These goods were already reserved. Assigning them will not deduct available stock again.</p><Select label="Existing order" required value={legacyId} onChange={e=>{setLegacyId(e.target.value);setLegacyWarehouse(data.legacyOrders.find(o=>o.id===e.target.value)?.pickupCenterId??'');}}><option value="">Choose order</option>{data.legacyOrders.map(o=><option key={o.id} value={o.id}>{o.id.slice(0,8)} · {o.pickupCenterName??'No pickup location'} · {o.status}</option>)}</Select><Select label="Reservation warehouse" required value={legacyWarehouse} onChange={e=>setLegacyWarehouse(e.target.value)}><option value="">Choose warehouse</option>{activeLocations.filter(w=>!data.legacyOrders.find(o=>o.id===legacyId)?.pickupCenterId||w.id===data.legacyOrders.find(o=>o.id===legacyId)?.pickupCenterId).map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</Select><Button type="submit" disabled={busy}>Assign reservation</Button></form></Card>}
 <details><summary className="cursor-pointer py-3 font-semibold">Warehouse movement history</summary>{historyError?<p role="alert" className="text-error">{historyError}</p>:!history?<p>Loading history…</p>:<><Card className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-xs"><thead><tr>{['Date / warehouse','Product / action','Available','Reserved','Reason / recorded by'].map(t=><th key={t} className="p-3">{t}</th>)}</tr></thead><tbody>{history.items.map(m=><tr key={m.id} className="border-t border-slate-100"><td className="p-3">{new Date(m.createdAt).toLocaleString('en-NG')}<p>{m.warehouseName}</p></td><td className="p-3"><p className="font-semibold">{m.productName}</p><p>{m.kind} · {m.unit}</p>{m.operationId&&<p className="text-text-muted">Ref {m.operationId.slice(0,8)}</p>}{m.orderId&&<Link className="text-primary underline" href={`/dashboard/orders/${m.orderId}/review`}>View order</Link>}</td><td className="p-3">{m.availableBefore} → {m.availableAfter}</td><td className="p-3">{m.reservedBefore} → {m.reservedAfter}</td><td className="p-3">{m.reason}<p>{m.reference}</p><p className="text-text-muted">{m.actorName??'Customer checkout'}</p></td></tr>)}</tbody></table>{!history.items.length&&<p className="p-6 text-text-muted">No warehouse movements recorded.</p>}</Card><div className="flex items-center justify-between py-3"><Button variant="ghost" disabled={historyPage===1} onClick={()=>setHistoryPage(p=>p-1)}>Previous</Button><p className="text-xs">Page {historyPage} · {history.total} entries</p><Button variant="ghost" disabled={historyPage*history.pageSize>=history.total} onClick={()=>setHistoryPage(p=>p+1)}>Next</Button></div></>}</details>
 </>}
 </section>;
}
