"use client";
import { useEffect, useState } from "react";
import { apiFetch, getRole } from "../../../../lib/auth";
import { Card, PageHeader } from "../../../../components/ui/Card";
import { Button } from "../../../../components/ui/Button";
import { Input, Select, Textarea } from "../../../../components/ui/Field";
import { PlusIcon, BoxIcon } from "../../../../components/ui/icons";
import PayablesPanel from "./PayablesPanel";

interface Supplier {id:string;name:string;contactName:string;email:string;phone:string;address:string;paymentTermsDays:number;isActive:boolean}
interface Product {id:string;name:string;unit:string}
interface Warehouse {id:string;name:string;address:string}
interface Line {id:string;productId:string;productName:string;unit:string;quantity:number;unitCost:number;received:number;rejected:number;remaining:number}
interface Receipt {id:string;number:string;deliveryReference:string;notes:string;createdAt:string;lines:{purchaseOrderLineId:string;accepted:number;rejected:number}[]}
interface PO {id:string;number:string;supplierId:string;supplierName:string;warehouseId:string;warehouseName:string;createdBy:string;status:string;version:number;notes:string;total:number;createdAt:string;closedReason?:string;lines:Line[];receipts:Receipt[]}
interface Draft {supplierId:string;warehouseId:string;notes:string;lines:{productId:string;quantity:string;unitCost:string}[]}
const emptySupplier = {name:"",contactName:"",email:"",phone:"",address:"",paymentTermsDays:0,isActive:true};
const money = (n:number) => new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN"}).format(n);
async function request<T>(path:string,options?:RequestInit):Promise<T> {const r=await apiFetch(`/v1/admin/purchasing${path}`,options);const body=await r.json();if(!r.ok) throw new Error(typeof body.message==="string"?body.message:"Check the form and try again.");return body;}

export default function PurchasingPage() {
 const [tab,setTab]=useState<"orders"|"suppliers"|"payables">("orders");
 const [suppliers,setSuppliers]=useState<Supplier[]>([]);const [orders,setOrders]=useState<PO[]>([]);
 const [products,setProducts]=useState<Product[]>([]);const [warehouses,setWarehouses]=useState<Warehouse[]>([]);
 const [selected,setSelected]=useState<PO|null>(null);const [draft,setDraft]=useState<Draft|null>(null);const [editId,setEditId]=useState<string|null>(null);
 const [supplierForm,setSupplierForm]=useState<typeof emptySupplier|null>(null);const [supplierId,setSupplierId]=useState<string|null>(null);
 const [reason,setReason]=useState("");const [receipt,setReceipt]=useState<{reference:string;notes:string;operationId:string;lines:{purchaseOrderLineId:string;accepted:string;rejected:string}[]}|null>(null);
 const [error,setError]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);
 const [actorId,setActorId]=useState("");
 const [filter,setFilter]=useState("");const [query,setQuery]=useState("");const [role,setRole]=useState<string|null>(null);
 async function load() {const [s,o]=await Promise.all([request<Supplier[]>("/suppliers"),request<PO[]>("/orders")]);setSuppliers(s);setOrders(o);}
 useEffect(()=>{let active=true;setRole(getRole());request<{staffId:string}>("/context").then(c=>{if(active)setActorId(c.staffId);}).catch(()=>{});const receiptId=new URLSearchParams(window.location.search).get("receipt");if(receiptId)request<PO>(`/receipts/${receiptId}`).then(po=>{if(active)setSelected(po);}).catch(e=>{if(active)setError(e.message);});Promise.all([request<Supplier[]>("/suppliers"),request<PO[]>("/orders"),apiFetch("/v1/admin/catalog/products").then(async r=>{if(!r.ok)throw new Error("Unable to load products");return r.json();}),apiFetch("/v1/pickup-centers").then(async r=>{if(!r.ok)throw new Error("Unable to load pickup warehouses");return r.json();})]).then(([s,o,p,w])=>{if(active){setSuppliers(s);setOrders(o);setProducts(p);setWarehouses(w);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
 async function run(work:()=>Promise<void>) {if(busy)return;setBusy(true);setError("");setNotice("");try {await work();}catch(e){setError(e instanceof Error?e.message:"Unable to complete action");}finally{setBusy(false);}}
 function newDraft() {setSelected(null);setReceipt(null);setEditId(null);setDraft({supplierId:"",warehouseId:"",notes:"",lines:[{productId:"",quantity:"1",unitCost:""}]});setError("");}
 async function open(id:string) {await run(async()=>{setSelected(await request<PO>(`/orders/${id}`));setDraft(null);setReceipt(null);setReason("");});}
 async function saveDraft(e:React.FormEvent) {e.preventDefault();if(!draft)return;await run(async()=>{const po=await request<PO>(editId?`/orders/${editId}`:"/orders",{method:editId?"PATCH":"POST",body:JSON.stringify({supplierId:draft.supplierId,warehouseId:draft.warehouseId,notes:draft.notes,lines:draft.lines.map(l=>({productId:l.productId,quantity:Number(l.quantity),unitCostNaira:Number(l.unitCost)})),...(editId?{version:selected?.version}:{})})});setDraft(null);setSelected(po);setNotice("Purchase order draft saved.");await load();});}
 async function action(action:string) {if(!selected)return;await run(async()=>{const po=await request<PO>(`/orders/${selected.id}/actions`,{method:"POST",body:JSON.stringify({action,version:selected.version,reason})});setSelected(po);setReason("");setNotice("Purchase order updated.");await load();});}
 async function saveSupplier(e:React.FormEvent) {e.preventDefault();if(!supplierForm)return;await run(async()=>{await request(supplierId?`/suppliers/${supplierId}`:"/suppliers",{method:supplierId?"PATCH":"POST",body:JSON.stringify(supplierForm)});setSupplierForm(null);setNotice("Supplier saved.");await load();});}
 async function saveReceipt(e:React.FormEvent) {e.preventDefault();if(!receipt||!selected)return;await run(async()=>{const lines=receipt.lines.map(l=>({purchaseOrderLineId:l.purchaseOrderLineId,accepted:Number(l.accepted),rejected:Number(l.rejected)})).filter(l=>l.accepted+l.rejected>0);if(!lines.length)throw new Error("Enter at least one accepted or rejected quantity.");const po=await request<PO>(`/orders/${selected.id}/receipts`,{method:"POST",body:JSON.stringify({deliveryReference:receipt.reference,notes:receipt.notes,operationId:receipt.operationId,lines})});setSelected(po);setReceipt(null);setNotice("Delivery recorded. Accepted goods were added to inventory once.");await load();});}
 function changeReceipt(update:Partial<NonNullable<typeof receipt>>) {setReceipt(r=>r?{...r,...update,operationId:crypto.randomUUID()}:r);}
 const visibleOrders=orders.filter(p=>(!filter||p.status===filter)&&`${p.number} ${p.supplierName} ${p.warehouseName}`.toLowerCase().includes(query.toLowerCase()));
 return <div className="space-y-5"><PageHeader title="Purchasing" description="Suppliers, warehouse deliveries, invoices and payments." action={tab!=="payables"?<Button disabled={busy} onClick={()=>tab==="orders"?newDraft():(setSupplierId(null),setSupplierForm({...emptySupplier}))}><PlusIcon className="h-4 w-4" />{tab==="orders"?"New purchase order":"Add supplier"}</Button>:undefined} />
  {error&&<p role="alert" className="rounded-lg bg-error/10 p-3 text-sm text-error">{error}</p>}{notice&&<p role="status" className="rounded-lg bg-primary/10 p-3 text-sm text-primary">{notice}</p>}
  <div className="flex flex-wrap gap-3"><Button variant={tab==="orders"?"primary":"ghost"} onClick={()=>setTab("orders")}>Purchase orders</Button><Button variant={tab==="suppliers"?"primary":"ghost"} onClick={()=>setTab("suppliers")}>Suppliers</Button><Button variant={tab==="payables"?"primary":"ghost"} onClick={()=>setTab("payables")}>Invoices & payments</Button></div>
  {loading?<p>Loading purchasing…</p>:tab==="payables"?<PayablesPanel orders={orders} actorId={actorId} role={role}/>:tab==="suppliers"?<>
   {supplierForm&&<Card className="p-5"><form onSubmit={saveSupplier} className="space-y-4"><h2 className="font-semibold">{supplierId?"Edit supplier":"New supplier"}</h2><div className="grid gap-4 sm:grid-cols-2">{(["name","contactName","email","phone","address"] as const).map(key=><Input key={key} label={{name:"Supplier name",contactName:"Contact person",email:"Email",phone:"Phone",address:"Address"}[key]} required={key==="name"} type={key==="email"?"email":"text"} value={supplierForm[key]} onChange={e=>setSupplierForm({...supplierForm,[key]:e.target.value})} />)}<Input label="Payment terms (days)" type="number" min="0" max="365" value={supplierForm.paymentTermsDays} onChange={e=>setSupplierForm({...supplierForm,paymentTermsDays:Number(e.target.value)})} /></div><label className="flex gap-2 text-sm"><input type="checkbox" checked={supplierForm.isActive} onChange={e=>setSupplierForm({...supplierForm,isActive:e.target.checked})} />Active supplier</label><div className="flex gap-3"><Button disabled={busy} type="submit">Save supplier</Button><Button disabled={busy} type="button" variant="ghost" onClick={()=>setSupplierForm(null)}>Cancel</Button></div></form></Card>}
   <div className="grid gap-4 md:grid-cols-2">{suppliers.map(s=><Card key={s.id} className="p-5"><div className="flex justify-between gap-3"><h2 className="font-semibold">{s.name}</h2><span className="text-xs text-text-muted">{s.isActive?"Active":"Inactive"}</span></div><p className="mt-2 text-sm text-text-muted">{s.contactName} {s.phone} {s.email}</p><p className="mt-2 text-sm">{s.address||"No address entered"}</p><p className="my-3 text-xs text-text-muted">Payment terms: {s.paymentTermsDays} days</p><Button variant="ghost" onClick={()=>{setSupplierId(s.id);setSupplierForm({...s});}}>Edit supplier</Button></Card>)}</div>{suppliers.length===0&&<Card className="p-8 text-center text-text-muted">Add your first supplier to begin purchasing.</Card>}
  </>:<>
   {!warehouses.length&&<p className="text-sm text-text-muted">Create an active pickup location before creating a purchase order. Pickup locations are used as warehouses.</p>}
   {draft&&<Card className="p-5"><form onSubmit={saveDraft} className="space-y-4"><h2 className="font-semibold">{editId?"Edit draft":"New purchase order"}</h2><div className="grid gap-4 sm:grid-cols-2"><Select label="Supplier" required value={draft.supplierId} onChange={e=>setDraft({...draft,supplierId:e.target.value})}><option value="">Choose supplier</option>{suppliers.filter(s=>s.isActive).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select><Select label="Receiving warehouse (pickup location)" required value={draft.warehouseId} onChange={e=>setDraft({...draft,warehouseId:e.target.value})}><option value="">Choose pickup warehouse</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</Select></div>
    {draft.lines.map((line,i)=><div key={i} className="grid items-end gap-3 rounded-xl bg-surface p-3 md:grid-cols-[2fr_1fr_1fr_auto]"><Select label="Product / stock unit" required value={line.productId} onChange={e=>setDraft({...draft,lines:draft.lines.map((l,j)=>j===i?{...l,productId:e.target.value}:l)})}><option value="">Choose product</option>{products.filter(p=>!draft.lines.some((l,j)=>j!==i&&l.productId===p.id)).map(p=><option key={p.id} value={p.id}>{p.name} · {p.unit}</option>)}</Select><Input required label="Quantity" type="number" min="1" max="1000000" step="1" value={line.quantity} onChange={e=>setDraft({...draft,lines:draft.lines.map((l,j)=>j===i?{...l,quantity:e.target.value}:l)})} /><Input required label="Unit cost (₦)" type="number" min="0.01" max="100000000" step="0.01" value={line.unitCost} onChange={e=>setDraft({...draft,lines:draft.lines.map((l,j)=>j===i?{...l,unitCost:e.target.value}:l)})} /><Button type="button" variant="ghost" disabled={draft.lines.length===1} onClick={()=>setDraft({...draft,lines:draft.lines.filter((_,j)=>j!==i)})}>Remove</Button></div>)}
    <Button type="button" variant="ghost" disabled={draft.lines.length>=100} onClick={()=>setDraft({...draft,lines:[...draft.lines,{productId:"",quantity:"1",unitCost:""}]})}>Add product</Button><Textarea label="Notes" maxLength={2000} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/><div className="flex gap-3"><Button type="submit" disabled={busy}>Save draft</Button><Button type="button" variant="ghost" disabled={busy} onClick={()=>setDraft(null)}>Cancel</Button></div></form></Card>}
   {selected&&!draft&&<Card className="space-y-4 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-bold">{selected.number}</h2><p className="mt-1 text-sm text-text-muted">{selected.supplierName} · {selected.warehouseName}</p></div><div className="text-right"><p className="capitalize text-primary">{selected.status.replaceAll("_"," ")}</p><p className="font-semibold">{money(selected.total)}</p></div></div><p className="text-sm">{selected.notes}</p>{selected.closedReason&&<p className="text-sm">Closure reason: {selected.closedReason}</p>}
    <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead><tr>{["Product / unit","Ordered","Unit cost","Accepted","Rejected","Remaining"].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{selected.lines.map(l=><tr key={l.id} className="border-t border-slate-100"><td className="p-3">{l.productName}<p className="text-xs text-text-muted">{l.unit}</p></td><td className="p-3">{l.quantity}</td><td className="p-3">{money(l.unitCost)}</td><td className="p-3">{l.received}</td><td className="p-3">{l.rejected}</td><td className="p-3">{l.remaining}</td></tr>)}</tbody></table></div>
    <div className="flex flex-wrap gap-2">{selected.status==="draft"&&selected.createdBy===actorId&&<><Button disabled={busy} onClick={()=>action("submit")}>Submit for approval</Button><Button variant="ghost" disabled={busy} onClick={()=>{setEditId(selected.id);setDraft({supplierId:selected.supplierId,warehouseId:selected.warehouseId,notes:selected.notes,lines:selected.lines.map(l=>({productId:l.productId,quantity:String(l.quantity),unitCost:String(l.unitCost)}))});}}>Edit draft</Button></>}{selected.status==="submitted"&&role==="super_admin"&&<><Button disabled={busy||!actorId||selected.createdBy===actorId} onClick={()=>action("approve")}>Approve</Button><Button variant="ghost" disabled={busy||reason.trim().length<3} onClick={()=>action("return")}>Return for changes</Button></>}{["approved","partially_received"].includes(selected.status)&&<Button disabled={busy} onClick={()=>setReceipt({reference:"",notes:"",operationId:crypto.randomUUID(),lines:selected.lines.map(l=>({purchaseOrderLineId:l.id,accepted:"0",rejected:"0"}))})}><BoxIcon className="h-4 w-4"/>Receive delivery</Button>}{["draft","submitted"].includes(selected.status)&&<Button variant="ghost" disabled={busy||reason.trim().length<3} onClick={()=>action("cancel")}>Cancel order</Button>}{["approved","partially_received","fully_received"].includes(selected.status)&&role==="super_admin"&&<Button variant="ghost" disabled={busy||reason.trim().length<3} onClick={()=>action("close")}>Close order</Button>}<Button variant="ghost" disabled={busy} onClick={()=>open(selected.id)}>Refresh order</Button><Button variant="ghost" disabled={busy} onClick={()=>{setSelected(null);setReceipt(null);}}>Back to list</Button></div>
    <Input label="Reason for return, cancellation or closing" minLength={3} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/><p className="text-xs text-text-muted">Approval requires a different super admin from the preparer. {selected.createdBy===actorId&&selected.status==="submitted"?"Ask another super admin to review this order.":""} Accepted goods go to {selected.warehouseName}; rejected goods never increase available stock.</p>
    {receipt&&<form onSubmit={saveReceipt} className="space-y-4 rounded-xl border border-emerald-100 bg-surface p-4"><h3 className="font-semibold">Receive at {selected.warehouseName}</h3><Input label="Supplier delivery reference" required minLength={2} maxLength={160} value={receipt.reference} onChange={e=>changeReceipt({reference:e.target.value})}/>{receipt.lines.map((r,i)=>{const l=selected.lines.find(l=>l.id===r.purchaseOrderLineId)!;return <div key={l.id} className="grid items-center gap-3 sm:grid-cols-3"><p className="text-sm">{l.productName}<span className="block text-xs text-text-muted">{l.remaining} {l.unit} outstanding</span></p><Input label="Accepted" type="number" min="0" max={l.remaining} step="1" value={r.accepted} onChange={e=>changeReceipt({lines:receipt.lines.map((line,j)=>j===i?{...line,accepted:e.target.value}:line)})}/><Input label="Rejected" type="number" min="0" max="1000000" step="1" value={r.rejected} onChange={e=>changeReceipt({lines:receipt.lines.map((line,j)=>j===i?{...line,rejected:e.target.value}:line)})}/></div>;})}<Textarea label="Delivery notes" maxLength={2000} value={receipt.notes} onChange={e=>changeReceipt({notes:e.target.value})}/><div className="flex gap-3"><Button type="submit" disabled={busy}>Post goods receipt</Button><Button type="button" variant="ghost" disabled={busy} onClick={()=>setReceipt(null)}>Cancel receipt</Button></div></form>}
    <h3 className="font-semibold">Goods receipts</h3>{selected.receipts.length===0?<p className="text-sm text-text-muted">No deliveries posted yet.</p>:selected.receipts.map(r=><div key={r.id} className="rounded-xl border border-slate-100 p-3 text-sm"><p className="font-semibold">{r.number} · {r.deliveryReference}</p><p className="mt-1 text-xs text-text-muted">{new Date(r.createdAt).toLocaleString("en-NG")} · {selected.warehouseName}</p>{r.lines.map(l=><p key={l.purchaseOrderLineId} className="mt-1">{selected.lines.find(p=>p.id===l.purchaseOrderLineId)?.productName}: {l.accepted} accepted, {l.rejected} rejected</p>)}<p className="text-xs text-text-muted">{r.notes}</p></div>)}
   </Card>}
   {!selected&&!draft&&<><div className="grid gap-3 sm:grid-cols-2"><Input label="Search orders" value={query} onChange={e=>setQuery(e.target.value)} placeholder="PO number, supplier or warehouse"/><Select label="Status" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All statuses</option>{["draft","submitted","approved","partially_received","fully_received","closed","cancelled"].map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</Select></div><Card className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead><tr>{["Purchase order","Supplier / warehouse","Status","Total","Action"].map(h=><th key={h} className="p-4">{h}</th>)}</tr></thead><tbody>{visibleOrders.map(p=><tr key={p.id} className="border-t border-slate-100"><td className="p-4 font-semibold">{p.number}</td><td className="p-4">{p.supplierName}<p className="text-xs text-text-muted">{p.warehouseName}</p></td><td className="p-4 capitalize">{p.status.replaceAll("_"," ")}</td><td className="p-4">{money(p.total)}</td><td className="p-4"><Button variant="ghost" disabled={busy} onClick={()=>open(p.id)}>View order</Button></td></tr>)}</tbody></table>{!visibleOrders.length&&<p className="p-8 text-center text-text-muted">No purchase orders match. Create a draft to get started.</p>}</Card></>}
  </>}
 </div>;
}
