"use client";
import { useEffect, useState } from "react";
import { apiFetch } from "../../../../lib/auth";
import { Card } from "../../../../components/ui/Card";
import { Button } from "../../../../components/ui/Button";
import { Input, Select, Textarea } from "../../../../components/ui/Field";

interface Order {id:string;number:string;supplierName:string;status:string}
interface MatchLine {id:string;productName:string;unit:string;unitCost:number;accepted:number;invoiced:number;remaining:number}
interface Matching {number:string;supplierName:string;paymentTermsDays:number;lines:MatchLine[]}
interface Payment {id:string;number:string;amount:number;paymentDate:string;method:string;reference:string;notes:string;reversal:null|{reason:string;createdAt:string}}
interface CreditNote {id:string;number:string;reference:string;amount:number;creditDate:string;reason:string;status:string;version:number;createdBy:string;voidReason?:string;reversal:null|{reason:string;createdAt:string}}
interface Invoice {id:string;number:string;reference:string;supplierId:string;supplierName:string;purchaseOrderId:string;status:string;paymentStatus:string;invoiceDate:string;dueDate:string;total:number;paid:number;credited:number;balance:number;supplierCredit:number;overdue:boolean;createdBy:string;version:number;notes:string;voidReason?:string;lines:{id:string;productName:string;unit:string;quantity:number;unitCost:number;total:number}[];payments:Payment[];creditNotes:CreditNote[]}
interface Overview {invoices:Invoice[];outstanding:number;overdue:number;paid:number;credited:number;supplierCredit:number;suppliers:{id:string;name:string;balance:number;overdue:number;supplierCredit:number}[]}
const money=(n:number)=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN"}).format(n);
const today=()=>new Date().toISOString().slice(0,10);
async function request<T>(path:string,options?:RequestInit):Promise<T> {
  const response=await apiFetch(`/v1/admin/purchasing/payables${path}`,options);
  const body=await response.json();
  if(!response.ok)throw new Error(typeof body.message==="string"?body.message:"Check the form and try again.");
  return body;
}
const post=(body:unknown):RequestInit=>({method:"POST",body:JSON.stringify(body)});

export default function PayablesPanel({orders,actorId,role}:{orders:Order[];actorId:string;role:string|null}) {
  const [data,setData]=useState<Overview|null>(null);
  const [selected,setSelected]=useState<Invoice|null>(null);
  const [matching,setMatching]=useState<Matching|null>(null);
  const [draft,setDraft]=useState<{purchaseOrderId:string;reference:string;invoiceDate:string;dueDate:string;notes:string;operationId:string;quantities:Record<string,string>}|null>(null);
  const [payment,setPayment]=useState<{amount:string;paymentDate:string;method:string;reference:string;notes:string;operationId:string}|null>(null);
  const [credit,setCredit]=useState<{amount:string;creditDate:string;reference:string;reason:string;operationId:string}|null>(null);
  const [reason,setReason]=useState("");
  const [error,setError]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);
  const [query,setQuery]=useState("");const [filter,setFilter]=useState("");
  async function reload(){setData(await request<Overview>(""));}
  useEffect(()=>{let active=true;request<Overview>("").then(d=>{if(active)setData(d);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
  async function run(work:()=>Promise<void>) {if(busy)return;setBusy(true);setError("");setNotice("");try{await work();}catch(e){setError(e instanceof Error?e.message:"Unable to complete action");}finally{setBusy(false);}}
  function newDraft(){setSelected(null);setMatching(null);setPayment(null);setCredit(null);setDraft({purchaseOrderId:"",reference:"",invoiceDate:today(),dueDate:today(),notes:"",operationId:crypto.randomUUID(),quantities:{}});}
  function changeDraft(update:Partial<NonNullable<typeof draft>>){setDraft(d=>d?{...d,...update,operationId:crypto.randomUUID()}:d);}
  function changePayment(update:Partial<NonNullable<typeof payment>>){setPayment(p=>p?{...p,...update,operationId:crypto.randomUUID()}:p);}
  function changeCredit(update:Partial<NonNullable<typeof credit>>){setCredit(c=>c?{...c,...update,operationId:crypto.randomUUID()}:c);}
  async function chooseOrder(id:string){changeDraft({purchaseOrderId:id,quantities:{}});setMatching(null);if(!id)return;await run(async()=>{const match=await request<Matching>(`/matching/${id}`);setMatching(match);const date=new Date(`${draft?.invoiceDate||today()}T00:00:00Z`);date.setUTCDate(date.getUTCDate()+match.paymentTermsDays);changeDraft({dueDate:date.toISOString().slice(0,10)});});}
  async function open(id:string){await run(async()=>{setSelected(await request<Invoice>(`/invoices/${id}`));setDraft(null);setPayment(null);setCredit(null);setReason("");});}
  async function saveInvoice(e:React.FormEvent){e.preventDefault();if(!draft||!matching)return;await run(async()=>{
    const lines=matching.lines.map(l=>({purchaseOrderLineId:l.id,quantity:Number(draft.quantities[l.id]||0)})).filter(l=>l.quantity>0);
    if(!lines.length)throw new Error("Enter at least one invoice quantity.");
    const {quantities,...header}=draft;
    setSelected(await request<Invoice>("/invoices",post({...header,lines})));setDraft(null);setNotice("Draft saved. A different super admin can review and post it.");await reload();
  });}
  async function action(action:"post"|"void"){if(!selected)return;await run(async()=>{setSelected(await request<Invoice>(`/invoices/${selected.id}/actions`,post({action,version:selected.version,reason})));setReason("");setNotice(action==="post"?"Invoice posted to supplier payables.":"Invoice voided; history retained.");await reload();});}
  async function savePayment(e:React.FormEvent){e.preventDefault();if(!payment||!selected)return;await run(async()=>{
    const {amount,...fields}=payment;setSelected(await request<Invoice>(`/invoices/${selected.id}/payments`,post({...fields,amountNaira:Number(amount)})));setPayment(null);setNotice("Payment recorded. No money was transferred by this app.");await reload();
  });}
  async function reverse(id:string){await run(async()=>{setSelected(await request<Invoice>(`/payments/${id}/reversal`,post({reason})));setReason("");setNotice("Payment record reversed. This does not refund or reverse a bank transfer.");await reload();});}
  async function saveCredit(e:React.FormEvent){e.preventDefault();if(!credit||!selected)return;await run(async()=>{const {amount,...fields}=credit;setSelected(await request<Invoice>(`/invoices/${selected.id}/credits`,post({...fields,amountNaira:Number(amount)})));setCredit(null);setNotice("Credit note draft saved. A different super admin must post it.");await reload();});}
  async function creditAction(note:CreditNote,action:"post"|"void"|"reverse"){await run(async()=>{setSelected(await request<Invoice>(`/credits/${note.id}/actions`,post({action,version:note.version,reason})));setReason("");setNotice(action==="post"?"Credit note posted. Supplier balances updated.":"Credit note corrected; history retained.");await reload();});}
  const visible=data?.invoices.filter(i=>`${i.number} ${i.reference} ${i.supplierName}`.toLowerCase().includes(query.toLowerCase())&&(!filter||(filter==="overdue"?i.overdue:i.paymentStatus===filter)))??[];
  return <section className="space-y-5" aria-label="Supplier invoices and payments">
    {error&&<p role="alert" className="rounded-xl bg-error/10 p-3 text-sm text-error">{error}</p>}
    {notice&&<p role="status" className="rounded-xl bg-primary/10 p-3 text-sm text-primary">{notice}</p>}
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Supplier invoices & payments</h2><p className="mt-1 text-sm text-text-muted">Match invoices to accepted deliveries and record payments already made.</p></div><Button disabled={busy} onClick={newDraft}>New supplier invoice</Button></div>
    {data&&<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Outstanding",data.outstanding],["Overdue",data.overdue],["Payments recorded",data.paid],["Credit owed by suppliers",data.supplierCredit]].map(([label,value])=><Card key={String(label)} className="p-5"><p className="text-xs font-semibold uppercase tracking-wide text-text-muted">{label}</p><p className="mt-2 text-2xl font-bold text-primary">{money(Number(value))}</p></Card>)}</div>}
    {draft&&<Card className="p-5"><form onSubmit={saveInvoice} className="space-y-4"><h3 className="font-semibold">Prepare invoice draft</h3><p className="text-sm text-text-muted">Quantities must have been accepted. Costs use the approved purchase order. Check that the total matches the supplier’s invoice before posting.</p>
      <Select label="Purchase order" required disabled={busy} value={draft.purchaseOrderId} onChange={e=>void chooseOrder(e.target.value)}><option value="">Choose received purchase order</option>{orders.filter(o=>["partially_received","fully_received","closed"].includes(o.status)).map(o=><option key={o.id} value={o.id}>{o.number} · {o.supplierName}</option>)}</Select>
      <div className="grid gap-4 sm:grid-cols-3"><Input label="Supplier invoice reference" required minLength={2} maxLength={160} value={draft.reference} onChange={e=>changeDraft({reference:e.target.value})}/><Input label="Invoice date" type="date" required max={today()} value={draft.invoiceDate} onChange={e=>changeDraft({invoiceDate:e.target.value})}/><Input label="Due date" type="date" required min={draft.invoiceDate} value={draft.dueDate} onChange={e=>changeDraft({dueDate:e.target.value})}/></div>
      {matching&&<><h4 className="text-sm font-semibold">{matching.number} · {matching.supplierName}</h4>{matching.lines.map(l=><div key={l.id} className="grid items-center gap-3 rounded-xl bg-surface p-3 sm:grid-cols-[2fr_1fr_1fr]"><div><p className="text-sm font-semibold">{l.productName}</p><p className="text-xs text-text-muted">{l.accepted} accepted · {l.invoiced} invoiced · {l.remaining} {l.unit} remaining</p></div><p className="text-sm">{money(l.unitCost)} / {l.unit}</p><Input label="Invoice quantity" type="number" min="0" max={l.remaining} step="1" disabled={l.remaining===0||busy} value={draft.quantities[l.id]||"0"} onChange={e=>changeDraft({quantities:{...draft.quantities,[l.id]:e.target.value}})}/></div>)}<p className="font-semibold">Draft total: {money(matching.lines.reduce((sum,l)=>sum+Number(draft.quantities[l.id]||0)*l.unitCost,0))}</p></>}
      <Textarea label="Invoice notes" maxLength={2000} value={draft.notes} onChange={e=>changeDraft({notes:e.target.value})}/><div className="flex gap-3"><Button type="submit" disabled={busy||!matching}>Save draft</Button><Button type="button" variant="ghost" disabled={busy} onClick={()=>setDraft(null)}>Cancel</Button></div>
    </form></Card>}
    {selected&&!draft&&<Card className="space-y-4 p-5"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="text-xl font-bold">{selected.number} · {selected.reference}</h3><p className="text-sm text-text-muted">{selected.supplierName} · Invoice {selected.invoiceDate} · Due {selected.dueDate}</p></div><div className="text-right"><p className="font-semibold capitalize text-primary">{selected.paymentStatus.replaceAll("_"," ")}{selected.overdue?" · Overdue":""}</p><p className="text-lg font-bold">{money(selected.balance)} outstanding</p></div></div>
      <p className="text-sm">Total {money(selected.total)} · Paid {money(selected.paid)} · Credited {money(selected.credited)}</p>{selected.supplierCredit>0&&<p className="rounded-xl bg-primary/10 p-3 text-sm text-primary">The supplier owes {money(selected.supplierCredit)} in credit. This is awaiting refund or future allocation; no refund or payment offset has been made by this app.</p>}<p className="text-sm text-text-muted">{selected.notes}</p>{selected.voidReason&&<p className="text-sm">Void reason: {selected.voidReason}</p>}
      <div className="overflow-x-auto"><table className="w-full min-w-[500px] text-left text-sm"><thead><tr>{["Product","Quantity","Unit cost","Total"].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{selected.lines.map(l=><tr key={l.id} className="border-t border-slate-100"><td className="p-3">{l.productName}</td><td className="p-3">{l.quantity} {l.unit}</td><td className="p-3">{money(l.unitCost)}</td><td className="p-3">{money(l.total)}</td></tr>)}</tbody></table></div>
      <div className="flex flex-wrap gap-3">{selected.status==="draft"&&role==="super_admin"&&<Button disabled={busy||!actorId||actorId===selected.createdBy} onClick={()=>void action("post")}>Post matched invoice</Button>}{selected.status==="posted"&&selected.balance>0&&role==="super_admin"&&<Button disabled={busy} onClick={()=>setPayment({amount:"",paymentDate:today(),method:"bank_transfer",reference:"",notes:"",operationId:crypto.randomUUID()})}>Record payment</Button>}{selected.status!=="void"&&selected.paid===0&&selected.credited===0&&role==="super_admin"&&<Button variant="ghost" disabled={busy||reason.trim().length<3} onClick={()=>void action("void")}>Void invoice</Button>}<Button variant="ghost" disabled={busy} onClick={()=>void open(selected.id)}>Refresh invoice</Button><Button variant="ghost" disabled={busy} onClick={()=>{setSelected(null);setPayment(null);setCredit(null);}}>Back to invoices</Button></div>
      {selected.status==="draft"&&<p className="text-xs text-text-muted">A different super admin must post this invoice. Drafts do not count towards supplier balances. To correct a draft, void it and create a new draft with a new supplier reference.</p>}
      {role==="super_admin"&&<Input label="Reason for voiding or reversing an invoice, payment or credit note" maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/>}
      <div className="flex flex-wrap items-center justify-between gap-3"><h4 className="font-semibold">Supplier credit notes</h4>{selected.status==="posted"&&selected.credited<selected.total&&<Button variant="ghost" disabled={busy} onClick={()=>{setPayment(null);setCredit({amount:"",creditDate:today(),reference:"",reason:"",operationId:crypto.randomUUID()});}}>Prepare credit note</Button>}</div>
      <p className="text-xs text-text-muted">Record the supplier’s credit document for a discount or invoice correction. Posted credits reduce the amount owed; they do not return stock or send refunds.</p>
      {credit&&<form onSubmit={saveCredit} className="space-y-4 rounded-xl border border-emerald-100 bg-surface p-4"><h4 className="font-semibold">Credit note draft</h4><div className="grid gap-4 sm:grid-cols-3"><Input label="Supplier credit reference" required minLength={2} maxLength={160} value={credit.reference} onChange={e=>changeCredit({reference:e.target.value})}/><Input label="Credit date" type="date" min={selected.invoiceDate} max={today()} required value={credit.creditDate} onChange={e=>changeCredit({creditDate:e.target.value})}/><Input label="Credit amount (₦)" type="number" min="0.01" max={selected.total-selected.credited} step="0.01" required value={credit.amount} onChange={e=>changeCredit({amount:e.target.value})}/></div><Textarea label="Credit reason" required minLength={3} maxLength={1000} value={credit.reason} onChange={e=>changeCredit({reason:e.target.value})}/><div className="flex gap-3"><Button type="submit" disabled={busy}>Save credit draft</Button><Button type="button" variant="ghost" disabled={busy} onClick={()=>setCredit(null)}>Cancel credit note</Button></div></form>}
      {!selected.creditNotes.length?<p className="text-sm text-text-muted">No credit notes recorded.</p>:selected.creditNotes.map(c=><div key={c.id} className="space-y-2 rounded-xl border border-slate-100 p-3"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-sm font-semibold">{c.number} · {c.reference} · {money(c.amount)}</p><p className="text-xs capitalize text-text-muted">{c.creditDate} · {c.reversal?"reversed":c.status}</p></div><div className="flex flex-wrap gap-2">{role==="super_admin"&&c.status==="draft"&&<><Button disabled={busy||!actorId||actorId===c.createdBy||selected.status!=="posted"} onClick={()=>void creditAction(c,"post")}>Post credit</Button><Button variant="ghost" disabled={busy||reason.trim().length<3} onClick={()=>void creditAction(c,"void")}>Void credit draft</Button></>}{role==="super_admin"&&c.status==="posted"&&!c.reversal&&<Button variant="ghost" disabled={busy||reason.trim().length<3} onClick={()=>void creditAction(c,"reverse")}>Reverse credit</Button>}</div></div><p className="text-sm">{c.reason}</p>{c.status==="draft"&&<p className="text-xs text-text-muted">Awaiting a different super admin’s review; balances are unchanged.</p>}{c.voidReason&&<p className="text-xs text-text-muted">Void: {c.voidReason}</p>}{c.reversal&&<p className="text-xs text-text-muted">Reversal: {c.reversal.reason}</p>}</div>)}
      {payment&&<form onSubmit={savePayment} className="space-y-4 rounded-xl border border-emerald-100 bg-surface p-4"><h4 className="font-semibold">Record a payment already made</h4><p className="text-sm text-text-muted">This records an external payment and reduces the payable balance. It does not send money.</p><div className="grid gap-4 sm:grid-cols-2"><Input label="Amount paid (₦)" type="number" min="0.01" max={selected.balance} step="0.01" required value={payment.amount} onChange={e=>changePayment({amount:e.target.value})}/><Input label="Payment date" type="date" min={selected.invoiceDate} max={today()} required value={payment.paymentDate} onChange={e=>changePayment({paymentDate:e.target.value})}/><Select label="Payment method" value={payment.method} onChange={e=>changePayment({method:e.target.value})}>{["bank_transfer","cash","cheque","other"].map(m=><option key={m} value={m}>{m.replaceAll("_"," ")}</option>)}</Select><Input label="Bank / payment reference" required minLength={2} maxLength={160} value={payment.reference} onChange={e=>changePayment({reference:e.target.value})}/></div><Textarea label="Payment notes" maxLength={2000} value={payment.notes} onChange={e=>changePayment({notes:e.target.value})}/><div className="flex gap-3"><Button type="submit" disabled={busy}>Record payment</Button><Button type="button" variant="ghost" disabled={busy} onClick={()=>setPayment(null)}>Cancel</Button></div></form>}
      <h4 className="font-semibold">Payment history</h4>{!selected.payments.length?<p className="text-sm text-text-muted">No payments recorded.</p>:selected.payments.map(p=><div key={p.id} className="rounded-xl border border-slate-100 p-3"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-sm font-semibold">{p.number} · {money(p.amount)}{p.reversal?" · Reversed":""}</p><p className="text-xs text-text-muted">{p.paymentDate} · {p.method.replaceAll("_"," ")} · {p.reference}</p></div>{!p.reversal&&role==="super_admin"&&<Button variant="ghost" disabled={busy||reason.trim().length<3} onClick={()=>void reverse(p.id)}>Reverse record</Button>}</div>{p.notes&&<p className="mt-2 text-sm">{p.notes}</p>}{p.reversal&&<p className="mt-2 text-sm text-text-muted">Reversal: {p.reversal.reason}. No bank refund was initiated.</p>}</div>)}
    </Card>}
    {!draft&&!selected&&<><div className="grid gap-4 sm:grid-cols-2"><Input label="Search invoices" placeholder="Invoice number, reference or supplier" value={query} onChange={e=>setQuery(e.target.value)}/><Select label="Payment status" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All invoices</option>{["draft","unpaid","partially_paid","paid","credited","credit_due","overdue","void"].map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</Select></div><Card className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead><tr>{["Invoice / supplier","Due date","Status","Total","Outstanding","Action"].map(h=><th key={h} className="p-4">{h}</th>)}</tr></thead><tbody>{visible.map(i=><tr key={i.id} className="border-t border-slate-100"><td className="p-4 font-semibold">{i.number} · {i.reference}<p className="text-xs font-normal text-text-muted">{i.supplierName}</p></td><td className="p-4">{i.dueDate}</td><td className="p-4 capitalize">{i.paymentStatus.replaceAll("_"," ")}{i.overdue&&<span className="block text-xs text-error">Overdue</span>}</td><td className="p-4">{money(i.total)}</td><td className="p-4 font-semibold text-primary">{money(i.balance)}</td><td className="p-4"><Button variant="ghost" disabled={busy} onClick={()=>void open(i.id)}>View invoice</Button></td></tr>)}</tbody></table>{!visible.length&&<p className="p-8 text-center text-text-muted">{data?"No matching invoices. Receive goods against a purchase order to prepare an invoice.":"Loading supplier balances…"}</p>}</Card>
      {data&&<Card className="p-5"><h3 className="mb-3 font-semibold">Supplier balances</h3>{data.suppliers.length===0?<p className="text-sm text-text-muted">No suppliers yet.</p>:data.suppliers.map(s=><div key={s.id} className="flex flex-wrap justify-between gap-2 border-t border-slate-100 py-3 text-sm"><span>{s.name}</span><span>{money(s.balance)} outstanding · {money(s.overdue)} overdue · {money(s.supplierCredit)} credit owed</span></div>)}</Card>}
    </>}
  </section>;
}
