"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {apiFetch,getRole} from "../../../../../lib/auth";
import {Card,PageHeader} from "../../../../../components/ui/Card";
import {Button} from "../../../../../components/ui/Button";
import {Input,Textarea} from "../../../../../components/ui/Field";
interface Lot{id:string;sequence:number;productName:string;unit:string;remainingQuantity:number;unitCost:number|null;value:number|null;source:string;version:number}
interface Product{id:string;name:string;sku:string|null;unit:string;onHand:number;reserved:number;tracked:number;knownValue:number;unknownUnits:number;complete:boolean;lots:Lot[]}
interface Overview{knownValue:number;unknownUnits:number;mismatches:number;complete:boolean;method:string;products:Product[]}
interface Report{from:string;to:string;revenue:number;knownCogs:number;grossMargin:number|null;missingUnits:number;complete:boolean;knownStockLoss:number;unknownLossUnits:number;orders:{id:string;deliveredAt:string;warehouseName:string|null;revenue:number;knownCogs:number;grossMargin:number|null;missingUnits:number;complete:boolean}[]}
const money=(n:number)=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN"}).format(n);
const today=()=>new Date().toISOString().slice(0,10);
const start=()=>{const d=new Date();d.setUTCDate(d.getUTCDate()-29);return d.toISOString().slice(0,10);};
async function request<T>(path:string,options?:RequestInit):Promise<T>{const response=await apiFetch(`/v1/admin/inventory/valuation${path}`,options);const body=await response.json();if(!response.ok)throw new Error(typeof body.message==="string"?body.message:"Unable to load valuation");return body;}
function csv(name:string,rows:(string|number)[][]){const cell=(v:string|number)=>`"${String(v).replace(/^[=+@-]/,"'$&").replaceAll('"','""')}"`;const url=URL.createObjectURL(new Blob(["\uFEFF"+rows.map(r=>r.map(cell).join(",")).join("\r\n")],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function ValuationPage(){
 const [data,setData]=useState<Overview|null>(null),[report,setReport]=useState<Report|null>(null);
 const [from,setFrom]=useState(start),[to,setTo]=useState(today),[query,setQuery]=useState("");
 const [productId,setProductId]=useState<string|null>(null),[form,setForm]=useState<{lot:Lot;cost:string;reason:string;operationId:string}|null>(null);
 const [error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[role,setRole]=useState<string|null>(null);
 const [page,setPage]=useState(1);
 useEffect(()=>{let active=true;setRole(getRole());Promise.all([request<Overview>(""),request<Report>(`/cogs?from=${start()}&to=${today()}`)]).then(([d,r])=>{if(active){setData(d);setReport(r);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
 async function run(work:()=>Promise<void>){if(busy)return;setBusy(true);setError("");setNotice("");try{await work();}catch(e){setError(e instanceof Error?e.message:"Unable to complete action");}finally{setBusy(false);}}
 async function refreshReport(e:React.FormEvent){e.preventDefault();await run(async()=>{setReport(await request<Report>(`/cogs?from=${from}&to=${to}`));});}
 async function save(e:React.FormEvent){e.preventDefault();if(!form)return;await run(async()=>{await request(`/lots/${form.lot.id}/cost`,{method:"POST",body:JSON.stringify({unitCostNaira:Number(form.cost),version:form.lot.version,reason:form.reason,operationId:form.operationId})});setForm(null);setData(await request<Overview>(""));setNotice("Cost assigned to remaining stock. Historical order costs were preserved.");});}
 const visible=data?.products.filter(p=>`${p.name} ${p.sku??""}`.toLowerCase().includes(query.toLowerCase()))??[];
 const selected=data?.products.find(p=>p.id===productId);
 return <div className="space-y-5"><Link href="/dashboard/inventory" className="text-sm font-semibold text-primary">← Inventory</Link><PageHeader title="Inventory valuation" description="FIFO stock value and costs of collected orders across pickup warehouses."/>
  {error&&<p role="alert" className="rounded-xl bg-error/10 p-3 text-sm text-error">{error}</p>}{notice&&<p role="status" className="rounded-xl bg-primary/10 p-3 text-sm text-primary">{notice}</p>}
  <Card className="p-4 text-sm text-text-muted">FIFO uses the oldest stock first across all warehouses. Reserved goods remain in stock value until collection. Unknown costs are excluded from known value; incomplete margins are not shown as profit.</Card>
  {!data&&!error&&<p>Loading valuation…</p>}
  {data&&<><div className="grid gap-4 sm:grid-cols-3">{[["Known stock value",money(data.knownValue)],["Units missing costs",data.unknownUnits],["Quantity mismatches",data.mismatches]].map(([label,value])=><Card key={String(label)} className="p-5"><p className="text-xs font-semibold uppercase text-text-muted">{label}</p><p className="mt-2 text-2xl font-bold text-primary">{value}</p></Card>)}</div>
   {!data.complete&&<p className="rounded-xl bg-amber-50 p-4 text-sm text-amber-800">Valuation is incomplete. Enter actual purchase costs for unknown lots; resolve any quantity mismatches before relying on the total. Selling prices are never used as purchase costs.</p>}
   <div className="flex flex-wrap items-end justify-between gap-3"><Input label="Search product / SKU" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/><Button variant="ghost" onClick={()=>csv(`inventory-valuation-${today()}.csv`,[["Product","Unit","On hand","Reserved","Known value NGN","Units missing costs","Complete"],...visible.map(p=>[p.name,p.unit,p.onHand,p.reserved,p.knownValue,p.unknownUnits,p.complete?"Yes":"No"])])}>Export valuation</Button></div>
   <Card className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead><tr>{["Product","On hand","Reserved","Known value","Missing costs","Action"].map(h=><th key={h} className="p-4">{h}</th>)}</tr></thead><tbody>{visible.slice((page-1)*10,page*10).map(p=><tr key={p.id} className="border-t border-slate-100"><td className="p-4 font-semibold">{p.name}<p className="text-xs font-normal text-text-muted">{p.unit} · {p.complete?"Complete":"Incomplete"}</p></td><td className="p-4">{p.onHand}</td><td className="p-4">{p.reserved}</td><td className="p-4">{money(p.knownValue)}</td><td className="p-4">{p.unknownUnits} units</td><td className="p-4"><Button variant="ghost" onClick={()=>{setProductId(p.id);setForm(null);}}>View cost lots</Button></td></tr>)}</tbody></table>{!visible.length&&<p className="p-5 text-text-muted">No matching products.</p>}<div className="flex justify-between gap-3 p-4"><Button variant="ghost" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</Button><p className="text-xs">Page {page} of {Math.max(1,Math.ceil(visible.length/10))}</p><Button variant="ghost" disabled={page*10>=visible.length} onClick={()=>setPage(p=>p+1)}>Next</Button></div></Card>
   {selected&&<Card className="space-y-4 p-5"><div className="flex justify-between gap-3"><h2 className="font-semibold">{selected.name} · remaining cost lots</h2><Button variant="ghost" onClick={()=>{setProductId(null);setForm(null);}}>Close lots</Button></div>{!selected.lots.length&&<p className="text-sm text-text-muted">No tracked lots remain. A mismatch can indicate a stock import outside the inventory workflow.</p>}{selected.lots.map(l=><div key={l.id} className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 py-3"><div><p className="text-sm font-semibold">Lot {l.sequence} · {l.remainingQuantity} {l.unit}</p><p className="text-xs text-text-muted">{l.source.replaceAll("_"," ")} · {l.unitCost===null?"Unknown cost":`${money(l.unitCost)} per ${l.unit}`}</p></div>{l.unitCost===null&&role==="super_admin"&&<Button variant="ghost" disabled={busy} onClick={()=>setForm({lot:l,cost:"",reason:"",operationId:crypto.randomUUID()})}>Assign actual cost</Button>}</div>)}
    {form&&<form onSubmit={save} className="space-y-3 rounded-xl bg-surface p-4"><h3 className="font-semibold">Assign cost to lot {form.lot.sequence}</h3><p className="text-xs text-text-muted">Applies to its remaining {form.lot.remainingQuantity} {form.lot.unit}. Use the actual purchase document. Known costs and historical COGS cannot be overwritten.</p><Input label="Purchase cost per stock unit (₦)" type="number" min="0" max="100000000" step="0.01" required value={form.cost} onChange={e=>setForm({...form,cost:e.target.value,operationId:crypto.randomUUID()})}/><Textarea label="Source document / reason" required minLength={3} maxLength={1000} value={form.reason} onChange={e=>setForm({...form,reason:e.target.value,operationId:crypto.randomUUID()})}/><div className="flex gap-3"><Button type="submit" disabled={busy}>Assign cost</Button><Button type="button" variant="ghost" disabled={busy} onClick={()=>setForm(null)}>Cancel</Button></div></form>}
   </Card>}
  </>}
  <Card className="space-y-4 p-5"><h2 className="text-xl font-bold">Cost of goods & gross product margin</h2><p className="text-sm text-text-muted">Collected orders only. Revenue excludes delivery and service fees. This is product gross margin, before business expenses and financing costs.</p><form onSubmit={refreshReport} className="flex flex-wrap items-end gap-3"><Input label="From (UTC)" type="date" required max={to} value={from} onChange={e=>setFrom(e.target.value)}/><Input label="To (UTC)" type="date" required min={from} value={to} onChange={e=>setTo(e.target.value)}/><Button type="submit" disabled={busy}>Run report</Button>{report&&<Button type="button" variant="ghost" onClick={()=>csv(`order-cogs-${report.from}-${report.to}.csv`,[["Order","Collected at","Product revenue NGN","Known COGS NGN","Missing cost units","Gross margin NGN","Complete"],...report.orders.map(o=>[o.id,o.deliveredAt,o.revenue,o.knownCogs,o.missingUnits,o.grossMargin??"Incomplete",o.complete?"Yes":"No"])])}>Export report</Button>}</form>
   {report&&<><p className="text-xs text-text-muted">Report: {report.from} to {report.to} (inclusive UTC dates)</p><div className="grid gap-3 sm:grid-cols-3">{[["Product revenue",money(report.revenue)],["Known COGS",money(report.knownCogs)],["Gross product margin",report.grossMargin===null?"Incomplete":money(report.grossMargin)]].map(([label,value])=><div key={label} className="rounded-xl bg-surface p-4"><p className="text-xs text-text-muted">{label}</p><p className="mt-2 font-bold">{value}</p></div>)}</div>{!report.complete&&<p className="text-sm text-amber-800">{report.orders.filter(o=>!o.complete).length} orders have incomplete costs ({report.missingUnits} units without costs). Historical unknown costs are retained.</p>}<p className="text-sm">Stock losses recorded: {money(report.knownStockLoss)} known value · {report.unknownLossUnits} units with unknown value.</p><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead><tr>{["Order / collection","Product revenue","Known COGS","Missing costs","Gross margin"].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{report.orders.map(o=><tr key={o.id} className="border-t border-slate-100"><td className="p-3"><Link href={`/dashboard/orders/${o.id}/review`} className="text-primary">{o.id.slice(0,8)}</Link><p className="text-xs text-text-muted">{new Date(o.deliveredAt).toLocaleDateString("en-NG")} · {o.warehouseName||"Legacy order"}</p></td><td className="p-3">{money(o.revenue)}</td><td className="p-3">{money(o.knownCogs)}</td><td className="p-3">{o.missingUnits}</td><td className="p-3">{o.grossMargin===null?"Incomplete":money(o.grossMargin)}</td></tr>)}</tbody></table>{!report.orders.length&&<p className="p-5 text-sm text-text-muted">No collected orders in this period.</p>}</div></>}
  </Card>
 </div>;
}
